---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 192.168.99.10 zabbix zabbix.4linux.com.br zabbix.dexter.com.br
        - 192.168.99.11 prometheus prometheus.dexter.com.br
        - 192.168.99.12 4flix 4flix.dexter.com.br
        - 192.168.99.13 graylog graylog.dexter.com.br
        
    - name: Configura hostname da VM
      hostname:
        name: prometheus

    - name: Adicionar usuario suporte
      user:
        name: suporte
        shell: /bin/bash
        password : $1$QbUARykG$p2nthVG8AkDvabKPHwboa1

    - name: Criando o arquivo 98_4linux
      copy:
        src: files/98_4linux
        dest: /etc/sudoers.d
        mode: 0644

    - name: Ajustando .bashrc do usuario vagrant
      lineinfile:
        path: /home/vagrant/.bashrc
        line: 'sudo su - suporte'

    - name: Instalando pacotes de dependencias para o curso
      yum:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - epel-release
        - python3
        - python3-pip
        - policycoreutils-python
        - git
        - wget
        - vim
        - net-tools

    - name: Criando o arquivo get-pip.py
      copy:
        src: files/get-pip.py
        dest: /tmp
        mode: 0644

    - name: Atualiza o pip com Python 3
      shell: python3 get-pip.py
      args:
        chdir: /tmp

    - name: Alterando arquivo do SELinux
      lineinfile: 
          path: /etc/selinux/config
          regexp: '^SELINUX='
          line: 'SELINUX=disabled'

    - name: Desabilitando o Firewall
      command: systemctl disable firewalld

    - name: Parando FirewallD
      command: systemctl stop firewalld
